version: '3.2'
services:
  base-ubuntu:
    build: ./base-ubuntu
  base-db:
    build: ./base-db
    command: echo "do nothing"
  db:
    build: ./db
    network_mode: host
    environment:
      PGPORT: 8082
      POSTGRES_DB: song
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - base-db
    volumes:
      - "db-data:/var/lib/postgresql/data/pgdata"
  id-db:
    build: ./id-db
    network_mode: host
    environment:
      PGPORT: 8088
      POSTGRES_DB: dcc_identifier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - base-db
    volumes:
      - "id-db-data:/var/lib/postgresql/data/pgdata"
  auth:
    build: ./auth
    network_mode: host
    environment:
      AUTH_PORT: 8084
    volumes:
      - "auth-data:/opt/dcc/auth_data"
  id:
    build: ./id
    network_mode: host
    environment:
      ID_PORT: 8086
      ID_JMX_PORT: 10017
      ID_MANAGEMENT_PORT: 8089
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 8088
      POSTGRES_DB: dcc_identifier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      AUTH_HOST: localhost
      AUTH_PORT: 8084
      AUTH_ENDPOINT: /check_token/
      AUTH_SERVER_CLIENTID:  3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
      AUTH_SERVER_CLIENTSECRET: v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
    depends_on:
      - base-ubuntu
      - id-db
      - auth
    volumes:
      - "./logs/id_logs:/opt/dcc/id_logs"
      - "./tools:/opt/dcc/tools"
  server:
    build: ./server
    network_mode: host
    environment:
      SERVER_PORT: 8080
      SERVER_MANAGEMENT_PORT: 8081
      SERVER_JMX_PORT: 10016
      AUTH_HOST: localhost
      AUTH_PORT: 8084
      AUTH_ENDPOINT: /check_token/
      AUTH_SERVER_CLIENTID:  3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
      AUTH_SERVER_CLIENTSECRET: v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
      AUTH_TOKEN: ad83ebde-a55c-11e7-abc4-cec278b6b50a
      ID_HOST: localhost
      ID_PORT: 8086
      DB_HOST: localhost
      DB_PORT: 8082
      DB_NAME: song
      DB_USER: postgres
      DB_PASSWORD: password
      STORAGE_SERVER_HOST: localhost
      STORAGE_SERVER_PORT: 8087
    depends_on:
      - base-ubuntu
      - db 
      - id
      - auth
    volumes:
      - "./logs/server_logs:/opt/dcc/server_logs"
      - "./tools:/opt/dcc/tools"
  client:
    build: ./client
    environment:
      AUTH_TOKEN: ad83ebde-a55c-11e7-abc4-cec278b6b50a
      SERVER_HOST: localhost
      SERVER_PORT: 8080
      CLIENT_STUDY_ID: ABC123
      CLIENT_DEBUG_ENABLED: "false"
    depends_on:
      - base-ubuntu
      - server
    volumes:
      - "./data/client:/opt/dcc/data"
      - "./tools:/opt/dcc/tools"
  minio:
    image: minio/minio:latest
    network_mode: host
    volumes:
      - "./data/minio:/opt/dcc/data"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_PORT: 8085
    deploy:
        restart_policy:
            delay: 10s
            max_attempts: 10
            window: 60s
    command: server --address=0.0.0.0:8085 /opt/dcc/data
  storage-server:
    build: ./storage-server
    network_mode: host
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_PORT: 8085
      MINIO_HOST: localhost
      AUTH_HOST: localhost
      AUTH_PORT: 8084
      AUTH_ENDPOINT: /check_token/
      AUTH_SERVER_CLIENTID:  3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
      AUTH_SERVER_CLIENTSECRET: v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
      SERVER_HOST: localhost
      SERVER_PORT: 8080
      STORAGE_SERVER_HOST: localhost
      STORAGE_SERVER_PORT: 8087
      STORAGE_SERVER_JMX_PORT: 10018
      STORAGE_SERVER_DATA_BUCKET: oicr.icgc
      STORAGE_SERVER_STATE_BUCKET: oicr.icgc
      STORAGE_SERVER_DATA_DIR: data
      STORAGE_SERVER_OBJECT_SENTINEL: heliograph
    depends_on:
      - base-ubuntu
      - minio
      - server
      - auth
    volumes:
      - "./logs/storage_server_logs:/opt/dcc/storage_server_logs"
      - "./tools:/opt/dcc/tools"
      - "./data:/opt/dcc/data"
  storage-client:
    build: ./storage-client
    environment:
      AUTH_TOKEN: ad83ebde-a55c-11e7-abc4-cec278b6b50a
      SERVER_HOST: localhost
      SERVER_PORT: 8080
      STORAGE_SERVER_HOST: localhost
      STORAGE_SERVER_PORT: 8087
    depends_on:
      - storage-server
      - server
    volumes:
      - "./data/storage-client:/opt/dcc/data"
      - "./tools:/opt/dcc/tools"
  #create-buckets:
  #  build: ./create-buckets
  #  network_mode: host
  #  environment:
  #    MINIO_ACCESS_KEY: minio
  #    MINIO_SECRET_KEY: minio123
  #    MINIO_PORT: 8085
  #    MINIO_HOST: localhost
  #    STORAGE_SERVER_DATA_BUCKET: oicr.icgc
  #    STORAGE_SERVER_STATE_BUCKET: oicr.icgc
  #    STORAGE_SERVER_DATA_DIR: data
  #    STORAGE_SERVER_OBJECT_SENTINEL: heliograph
  #  volumes:
  #    - "./create-buckets/scripts:/opt/dcc/scripts"

volumes:
    db-data: {}
    id-db-data: {}
    auth-data: {}
