version: '3.2'
services:
  server:
    build: ./server
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 9090
      AUTH_ENDPOINT: /check_token/
      AUTH_SERVER_CLIENTID:  3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
      AUTH_SERVER_CLIENTSECRET: v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
      AUTH_TOKEN: ad83ebde-a55c-11e7-abc4-cec278b6b50a
      ID_HOST: id
      ID_PORT: 8443
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: song
      DB_USER: postgres
      DB_PASSWORD: password
      STORAGE_SERVER_HOST: localhost
      STORAGE_SERVER_PORT: 5000
    depends_on:
      - base-ubuntu
      - db 
      - id
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "./logs/server_logs:/opt/dcc/server_logs"
      - "./tools:/opt/dcc/tools"
  base-ubuntu:
    build: ./base-ubuntu
  base-db:
    build: ./base-db
    command: echo "do nothing"
  client:
    build: ./client
    environment:
      AUTH_TOKEN: ad83ebde-a55c-11e7-abc4-cec278b6b50a
      SERVER_HOST: localhost
      SERVER_PORT: 8080
      CLIENT_STUDY_ID: ABC123
      CLIENT_DEBUG_ENABLED: "false"
    depends_on:
      - base-ubuntu
      - server
    volumes:
      - "./data/client:/opt/dcc/data"
      - "./tools:/opt/dcc/tools"
  auth:
    build: ./auth
    environment:
      AUTH_PORT: 9090
    ports:
      - "9090:9090"
    volumes:
      - "auth-data:/opt/dcc/auth_data"
  db:
    build: ./db
    environment:
      POSTGRES_DB: song
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    depends_on:
      - base-db
    volumes:
      - "db-data:/var/lib/postgresql/data/pgdata"
  storage-client:
    build: ./storage-client
    env_file: ./env_config/common.env
    depends_on:
      - storage-server
      - server
    volumes:
      - "./data/storage-client:/opt/dcc/data"
  minio:
    image: minio/minio:latest
    network_mode: host
    volumes:
      - "./data/minio:/opt/dcc/data"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_PORT: 9999
    deploy:
        restart_policy:
            delay: 10s
            max_attempts: 10
            window: 60s
    command: server --address=localhost:9999 /opt/dcc/data
  storage-server:
    build: ./storage-server
    network_mode: host
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_PORT: 9999
      MINIO_HOST: localhost
      AUTH_HOST: auth
      AUTH_PORT: 9090
      AUTH_ENDPOINT: /check_token/
      AUTH_SERVER_CLIENTID:  3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
      AUTH_SERVER_CLIENTSECRET: v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
      SERVER_HOST: localhost
      SERVER_PORT: 8087
      STORAGE_SERVER_HOST: localhost
      STORAGE_SERVER_PORT: 5000
    depends_on:
      - base-ubuntu
      - minio
      - server
    volumes:
      - "./logs/storage_server_logs:/opt/dcc/storage_server_logs"
      - "./tools:/opt/dcc/tools"
  id:
    build: ./id
    environment:
      POSTGRES_HOST: id-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: dcc_identifier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      AUTH_HOST: auth
      AUTH_PORT: 9090
      AUTH_ENDPOINT: /check_token/
      AUTH_SERVER_CLIENTID:  3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP
      AUTH_SERVER_CLIENTSECRET: v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e
    depends_on:
      - base-ubuntu
      - id-db
    expose:
      - "8443"
    volumes:
      - "./logs/id_logs:/opt/dcc/id_logs"
  id-db:
    build: ./id-db
    environment:
      POSTGRES_DB: dcc_identifier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - base-db
    volumes:
      - "id-db-data:/var/lib/postgresql/data/pgdata"

volumes:
    db-data: {}
    id-db-data: {}
    auth-data: {}
