version: '3.2'
services:
  song:
    build: ./song
    volumes:
      - type: bind
        source: ./song/logs
        target: /opt/dcc/ext_logs
    depends_on:
      - db 
      - id
    ports:
      - "8080:8080"
  auth:
    build: ./auth
    volumes:
      - type: bind
        source: ./data/simple-auth-data
        target: /opt/dcc/simple-auth-data
    ports:
      - "8001:8000"
  db:
    build: ./song-db
  id:
    build: ./id
    depends_on:
      - id-db
    ports:
      - "8443:8443"
  id-db:
    build: ./id-db
