version: '3.2'
services:
  song:
    build: ./song
    volumes:
      - type: bind
        source: ./logs/song_logs
        target: /opt/dcc/song_logs
    depends_on:
      - db 
      - id
    ports:
      - "8080:8080"
  auth:
    build: ./auth
    volumes:
      - "auth-data:/opt/dcc/auth_data"
    ports:
      - "9090:9090"
  db:
    build: ./song-db
    ports:
      - "15432:5432"
    volumes:
      - "song-db-data:/var/lib/postgresql/data/pgdata"
      - type: bind
        source: ./logs/song_db_logs
        target: /opt/dcc/song_db_logs
  dcc-storage-client:
    build: ./dcc-storage-client
    depends_on:
      - dcc-storage-server
      - song
    volumes:
      - type: bind
        source: ./data/dcc-storage-client
        target: /opt/dcc/data
  icgc-storage-client:
    image: icgc/icgc-storage-client:latest
    volumes:
      - type: bind
        source: ./data/icgc-storage-client
        target: /data
    command: cp -r /icgc/icgc-storage-client/* /data
  minio:
    image: minio/minio:latest
    volumes:
      - type: bind
        source: ./data/minio
        target: /opt/dcc/data
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    deploy:
        restart_policy:
            delay: 10s
            max_attempts: 10
            window: 60s
    command: server /opt/dcc/data
  dcc-storage-server:
    build: ./dcc-storage-server
    depends_on:
      - minio
    ports:
      - "5000:5000"
  id:
    build: ./id
    depends_on:
      - id-db
    volumes:
      - type: bind
        source: ./logs/id_logs
        target: /opt/dcc/id_logs
    ports:
      - "8444:8444"
      - "8443:8443"
  id-db:
    build: ./id-db
    volumes:
      - "id-db-data:/var/lib/postgresql/data/pgdata"
      - type: bind
        source: ./logs/id_db_logs
        target: /opt/dcc/id_db_logs

volumes:
    song-db-data: {}
    id-db-data: {}
    auth-data: {}
